# Desafio - Gráficos

### 1. Genere una submuestra de casos

In [17]:
import pandas as pd
import numpy as np

np.random.seed(4053)
df = pd.read_csv('./qog_std_cs_jan18.csv')
nRows,_ = df.shape

subSample = df.loc[np.random.choice(nRows, int(nRows/2), False), ['undp_hdi', 'ccodealp', 'ht_region', 'gle_cgdpc', 'imf_pop', 'ffp_hf', 'wef_qes', 'wdi_expedu', 'wdi_ners']]
subSample

,undp_hdi,ccodealp,ht_region,gle_cgdpc,imf_pop,ffp_hf,wef_qes,wdi_expedu,wdi_ners
11,0.823,BHR,3,22498.4800,1.268000,3.5,4.319010,2.46746,88.250397
185,0.519,TZA,4,1416.3000,43.880001,7.0,3.004210,3.47914,NaN
53,0.582,GNQ,4,15412.4300,NaN,6.0,NaN,NaN,NaN
114,0.804,MNE,1,14538.5200,0.622000,3.6,4.253060,NaN,NaN
34,0.394,TCD,4,1651.0500,NaN,8.6,2.528029,2.84971,NaN
...,...,...,...,...,...,...,...,...,...
58,0.893,FIN,5,36958.2110,5.427000,2.3,5.859115,7.16810,94.003181
73,0.623,HND,2,3303.1399,NaN,6.9,3.180158,5.86775,49.259361
74,0.834,HUN,1,18310.8110,9.877000,3.3,3.289020,4.65935,92.195374
2,0.743,DZA,3,5402.1699,39.113998,5.1,2.977302,NaN,NaN
131,0.548,PAK,8,2855.5500,186.190002,7.0,3.381112,2.46435,41.175350

### 2. Genere una función que ingrese su objeto y devuelva: ...